In [1]:
from gensim.models import Word2Vec, KeyedVectors
pathToGoogleNews300 = '..//fromBlogOfShaneLynnWordEmbeddingsWithSpacyAndGensim_GoogleNews300//data//GoogleNews-vectors-negative300.bin'
#pathToGoogleNews300 = 'data\GoogleNews-vectors-negative300.bin'
model = KeyedVectors.load_word2vec_format(pathToGoogleNews300, binary=True)

In [2]:
model.doesnt_match("man woman child kitchen".split())

C:\Users\Eric\anaconda3\lib\site-packages\gensim\models\keyedvectors.py:877: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  vectors = vstack(self.word_vec(word, use_norm=True) for word in used_words).astype(REAL)

'kitchen'

In [3]:
model.most_similar(positive=['king', 'woman'], negative=['man'])

[('queen', 0.7118192911148071),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431607246399),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321243286133),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134343147278),
 ('sultan', 0.5098593235015869),
 ('monarchy', 0.5087411999702454)]

In [4]:
model.most_similar("man")

[('woman', 0.7664012312889099),
 ('boy', 0.6824870109558105),
 ('teenager', 0.6586930751800537),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409236907959),
 ('teen_ager', 0.5549196004867554),
 ('men', 0.5489763021469116)]

In [5]:
import pandas as pd

pathToGungorVict = '..//..//DS7004//u1720146_DS7004_courseworkCodeAndData//preparationWorks//fromDS7003_Gungor2018VictorianAuthorAttribution_NGram//Gungor_2018_VictorianAuthorAttribution_data-train.csv'
gungorVictRow = pd.read_csv(pathToGungorVict, encoding = 'ISO-8859-1')
#48: Washington Irving/ 13: Frances Hodgson Burnett/ 22: Jacob Abbott/ 25: James Payn/ 36: Oliver Optic

In [6]:
burnett13 = gungorVictRow.loc[gungorVictRow['author'] == 13]

abbott22 = gungorVictRow.loc[gungorVictRow['author'] == 22]

b13a22 = burnett13.append(abbott22, ignore_index=True)

test = b13a22.sample(frac=0.3, random_state=42)
test = test.reset_index()

train = b13a22.drop(test.index)
train = train.sample(frac=1, random_state=42).reset_index()

In [ ]:
authorsLines = gungorVictRow.loc[gungorVictRow['author'] == 48]
for i in [13, 22, 25, 36]:
    authorsLines = authorsLines.append(gungorVictRow.loc[gungorVictRow['author'] == i])

In [24]:
pd.DataFrame(authorsLines.author.value_counts())

    author
48    1825
25    1159
36     693
22     495
13     485

In [7]:
test = authorsLines.sample(frac=0.3, random_state=42)

train = authorsLines.drop(test.index)
train = train.sample(frac=1, random_state=42).reset_index()
test = test.reset_index()

In [8]:
print(test.index)

RangeIndex(start=0, stop=1397, step=1)

In [9]:
print(train.index)

RangeIndex(start=0, stop=3260, step=1)

In [10]:
test

      index                                               text  author
0     51850  rested in the the earth and nature seems to la...      48
1     52122  ready to cry out and ruin â so these are perpe...      48
2     50972  dart i do not find that they ever treated thei...      48
3     51293  were vain and that the government thought of h...      48
4     51261  ity of travelling over the c compass of nature...      48
...     ...                                                ...     ...
1392  52155  journey cheerily along the course of the soft ...      48
1393  26179  scheme she could hit upon if it could but be a...      25
1394  51359  new as into a snug elbow chair â and fell into...      48
1395  25702  with apparently the self same groups of childr...      25
1396  50945  own and to around the fun in as thinks proper ...      48

[1397 rows x 3 columns]

In [11]:
test.iloc[18:34]

    index                                               text  author
18  13636  fair at miss s remarks and then suddenly she b...      13
19  52113  date the rise of parties in this province cert...      48
20  37628  until a warrant had been obtained replied mr i...      36
21  25933  in all my professional experience lord if you ...      25
22  24193  learned but i that you would let me try and se...      22
23  26175  two at least of the little company in place we...      25
24  37543  been proud to exhibit as specimens of his art ...      36
25  52451  condition â for having made them with the comf...      48
26  24425  henry climbed up to reach the are you sure wil...      22
27  52183  the preliminary chapters with the discovery po...      48
28  13582  was still beating fast and as the white light ...      13
29  37979  by the attention of the governor of several of...      36
30  37573  but put him to bed and let him sleep it off i ...      36
31  51971  gained him an entrance into this habitation th...      48
32  13658  privately remarked miss whose tastes had not b...      13
33  24443  with it it was yours s aid i allow but not by ...      22

In [12]:
train

      index                                               text  author
0     13621  and strange happiness and strange life for two...      13
1     51143  its rough course below and a view of the with ...      48
2     52175  is the triumph of his skill to detect and drag...      48
3     25948  man will be grateful and faithful as for faith...      25
4     37786  his lifetime use such language i ll be bound h...      36
...     ...                                                ...     ...
3255  52538  consult character to establish and interest to...      48
3256  52581  of government and tasted the sweets of absolut...      48
3257  13233  rose from her seat trembling i will go away a ...      13
3258  52201  body with concerns above his nor thrust his no...      48
3259  37985  in holland and we must do as the did added t i...      36

[3260 rows x 3 columns]

In [13]:
train[35:55]

    index                                               text  author
35  51974  four and twenty years before he ascertained th...      48
36  13445  own and he saw a thing which lay hid in their ...      13
37  51302  of the organ entirely done away a description ...      48
38  51324  water moving from east to west by day and glid...      48
39  26411  work whom was more pleased to see than she wou...      25
40  37864  some other time replied as he hastened down th...      36
41  13612  had been packed up the sitting room struck him...      13
42  24561  and in the meantime all the work of tion must ...      22
43  51549  it might here be proved and i will perhaps at ...      48
44  37746  but the finally submitted and there was a bett...      36
45  37645  hear that added uncle appealing to the visitor...      36
46  37955  is not surpassed by that of any country in the...      36
47  24328  stopped to wrap herself in her cloak and then ...      22
48  51398  loaded with a of vines bowing their branches t...      48
49  25817  nature that should be even by however the lis ...      25
50  24418  what is it called then the garret what is the ...      22
51  13629  chairs all the most she had received had been ...      13
52  51385  great ease and little study in the course of o...      48
53  26296  his own good faith being attacked as well as t...      25
54  51428  make peace to the petty powers or as the india...      48

In [14]:
import gensim
all_stopwords = set(gensim.parsing.preprocessing.STOPWORDS)
all_stopwords

{'a',
 'about',
 'above',
 'across',
 'after',
 'afterwards',
 'again',
 'against',
 'all',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'amoungst',
 'amount',
 'an',
 'and',
 'another',
 'any',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anywhere',
 'are',
 'around',
 'as',
 'at',
 'back',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'below',
 'beside',
 'besides',
 'between',
 'beyond',
 'bill',
 'both',
 'bottom',
 'but',
 'by',
 'call',
 'can',
 'cannot',
 'cant',
 'co',
 'computer',
 'con',
 'could',
 'couldnt',
 'cry',
 'de',
 'describe',
 'detail',
 'did',
 'didn',
 'do',
 'does',
 'doesn',
 'doing',
 'don',
 'done',
 'down',
 'due',
 'during',
 'each',
 'eg',
 'eight',
 'either',
 'eleven',
 'else',
 'elsewhere',
 'empty',
 'enough',
 'etc',
 'even',
 'ever',
 'every',
 'everyone',
 'everything',
 'everywhere',
 'except',
 'few',
 'fifteen',
 'fifty',
 'fill',
 'find',
 'fire',
 'first',
 'five',
 'for',
 'former',
 'formerly',
 'forty',
 'found',
 'four',
 'from',
 'front',
 'full',
 'further',
 'get',
 'give',
 'go',
 'had',
 'has',
 'hasnt',
 'have',
 'he',
 'hence',
 'her',
 'here',
 'hereafter',
 'hereby',
 'herein',
 'hereupon',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'however',
 'hundred',
 'i',
 'ie',
 'if',
 'in',
 'inc',
 'indeed',
 'interest',
 'into',
 'is',
 'it',
 'its',
 'itself',
 'just',
 'keep',
 'kg',
 'km',
 'last',
 'latter',
 'latterly',
 'least',
 'less',
 'ltd',
 'made',
 'make',
 'many',
 'may',
 'me',
 'meanwhile',
 'might',
 'mill',
 'mine',
 'more',
 'moreover',
 'most',
 'mostly',
 'move',
 'much',
 'must',
 'my',
 'myself',
 'name',
 'namely',
 'neither',
 'never',
 'nevertheless',
 'next',
 'nine',
 'no',
 'nobody',
 'none',
 'noone',
 'nor',
 'not',
 'nothing',
 'now',
 'nowhere',
 'of',
 'off',
 'often',
 'on',
 'once',
 'one',
 'only',
 'onto',
 'or',
 'other',
 'others',
 'otherwise',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'part',
 'per',
 'perhaps',
 'please',
 'put',
 'quite',
 'rather',
 're',
 'really',
 'regarding',
 'same',
 'say',
 'see',
 'seem',
 'seemed',
 'seeming',
 'seems',
 'serious',
 'several',
 'she',
 'should',
 'show',
 'side',
 'since',
 'sincere',
 'six',
 'sixty',
 'so',
 'some',
 'somehow',
 'someone',
 'something',
 'sometime',
 'sometimes',
 'somewhere',
 'still',
 'such',
 'system',
 'take',
 'ten',
 'than',
 'that',
 'the',
 'their',
 'them',
 'themselves',
 'then',
 'thence',
 'there',
 'thereafter',
 'thereby',
 'therefore',
 'therein',
 'thereupon',
 'these',
 'they',
 'thick',
 'thin',
 'third',
 'this',
 'those',
 'though',
 'three',
 'through',
 'throughout',
 'thru',
 'thus',
 'to',
 'together',
 'too',
 'top',
 'toward',
 'towards',
 'twelve',
 'twenty',
 'two',
 'un',
 'under',
 'unless',
 'until',
 'up',
 'upon',
 'us',
 'used',
 'using',
 'various',
 'very',
 'via',
 'was',
 'we',
 'well',
 'were',
 'what',
 'whatever',
 'when',
 'whence',
 'whenever',
 'where',
 'whereafter',
 'whereas',
 'whereby',
 'wherein',
 'whereupon',
 'wherever',
 'whether',
 'which',
 'while',
 'whither',
 'who',
 'whoever',
 'whole',
 'whom',
 'whose',
 'why',
 'will',
 'with',
 'within',
 'without',
 'would',
 'yet',
 'you',
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [15]:
#be careful: nword and counter must be integers --Chiu
import numpy as np  # Make sure that numpy is imported

def makeFeatureVec(words, model, num_features):
    # Function to average all of the word vectors in a given
    # paragraph
    #
    # Pre-initialize an empty numpy array (for speed)
    featureVec = np.zeros((num_features,),dtype="float32")
    #
    nwords = 0
    # 
    # Index2word is a list that contains the names of the words in 
    # the model's vocabulary. Convert it to a set, for speed 
    index2word_set = set(model.wv.index2word)
    index2word_set2 = all_stopwords
    #
    # Loop over each word in the review and, if it is in the model's
    # vocaublary, add its feature vector to the total
    for word in words:
        if word in index2word_set and word in index2word_set2: 
            nwords = nwords + 1
            featureVec = np.add(featureVec,model[word])
    # 
    # Divide the result by the number of words to get the average
    if nwords == 0:
        nwords = 1
    featureVec = np.divide(featureVec,nwords)
    return featureVec


def getAvgFeatureVecs(reviews, model, num_features):
    # Given a set of reviews (each one a list of words), calculate 
    # the average feature vector for each one and return a 2D numpy array 
    # 
    # Initialize a counter
    counter = 0
    # 
    # Preallocate a 2D numpy array, for speed
    reviewFeatureVecs = np.zeros((len(reviews),num_features),dtype="float32")
    # 
    # Loop through the reviews
    for review in reviews:
       #
       # Print a status message every 1000th review
        if counter%50 == 0:
            haha = counter; hihi = len(reviews)
            print(f"Review {haha} of {hihi}") #% (counter, len(reviews))
       # 
       # Call the function (defined above) that makes average feature vectors
        #reviewFeatureVecs[counter] = makeFeatureVec(review, model, num_features)
        reviewFeatureVecs[counter] = makeFeatureVec(review, model, num_features)
       #
       # Increment the counter
        counter = counter + 1
    return reviewFeatureVecs

In [16]:
# Import various modules for string cleaning
from bs4 import BeautifulSoup
import re
from nltk.corpus import stopwords

def review_to_wordlist( review, remove_stopwords=False ):
    # Function to convert a document to a sequence of words,
    # optionally removing stop words.  Returns a list of words.
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(review).get_text()
    #  
    # 2. Remove non-letters
    review_text = re.sub("[^a-zA-Z]"," ", review_text)
    #
    # 3. Convert words to lower case and split them
    words = review_text.lower().split()
    #
    # 4. Optionally remove stop words (false by default)
    if remove_stopwords:
        stops = set(stopwords.words("english"))
        words = [w for w in words if not w in stops]
    #
    # 5. Return a list of words
    return(words)

In [17]:
# ****************************************************************
# Calculate average feature vectors for training and testing sets,
# using the functions we defined above. Notice that we now use stop word
# removal.
num_features = 300
clean_train_reviews = []
for review in train["text"]:
    #clean_train_reviews.append( review_to_wordlist( review, \
        #remove_stopwords=True ))
    clean_train_reviews.append( review_to_wordlist( review ))

trainDataVecs = getAvgFeatureVecs( clean_train_reviews, model, num_features )

print("Creating average feature vecs for test reviews")
clean_test_reviews = []
for review in test["text"]:
    #clean_test_reviews.append( review_to_wordlist( review, remove_stopwords=True ))
    clean_test_reviews.append( review_to_wordlist( review ))

testDataVecs = getAvgFeatureVecs( clean_test_reviews, model, num_features )

Review 0 of 3260

<ipython-input-15-8856e0a8f420>:15: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  index2word_set = set(model.wv.index2word)

Review 50 of 3260
Review 100 of 3260
Review 150 of 3260
Review 200 of 3260
Review 250 of 3260
Review 300 of 3260
Review 350 of 3260
Review 400 of 3260
Review 450 of 3260
Review 500 of 3260
Review 550 of 3260
Review 600 of 3260
Review 650 of 3260
Review 700 of 3260
Review 750 of 3260
Review 800 of 3260
Review 850 of 3260
Review 900 of 3260
Review 950 of 3260
Review 1000 of 3260
Review 1050 of 3260
Review 1100 of 3260
Review 1150 of 3260
Review 1200 of 3260
Review 1250 of 3260
Review 1300 of 3260
Review 1350 of 3260
Review 1400 of 3260
Review 1450 of 3260
Review 1500 of 3260
Review 1550 of 3260
Review 1600 of 3260
Review 1650 of 3260
Review 1700 of 3260
Review 1750 of 3260
Review 1800 of 3260
Review 1850 of 3260
Review 1900 of 3260
Review 1950 of 3260
Review 2000 of 3260
Review 2050 of 3260
Review 2100 of 3260
Review 2150 of 3260
Review 2200 of 3260
Review 2250 of 3260
Review 2300 of 3260
Review 2350 of 3260
Review 2400 of 3260
Review 2450 of 3260
Review 2500 of 3260
Review 2550 of 3260
Review 2600 of 3260
Review 2650 of 3260
Review 2700 of 3260
Review 2750 of 3260
Review 2800 of 3260
Review 2850 of 3260
Review 2900 of 3260
Review 2950 of 3260
Review 3000 of 3260
Review 3050 of 3260
Review 3100 of 3260
Review 3150 of 3260
Review 3200 of 3260
Review 3250 of 3260
Creating average feature vecs for test reviews
Review 0 of 1397
Review 50 of 1397
Review 100 of 1397
Review 150 of 1397
Review 200 of 1397
Review 250 of 1397
Review 300 of 1397
Review 350 of 1397
Review 400 of 1397
Review 450 of 1397
Review 500 of 1397
Review 550 of 1397
Review 600 of 1397
Review 650 of 1397
Review 700 of 1397
Review 750 of 1397
Review 800 of 1397
Review 850 of 1397
Review 900 of 1397
Review 950 of 1397
Review 1000 of 1397
Review 1050 of 1397
Review 1100 of 1397
Review 1150 of 1397
Review 1200 of 1397
Review 1250 of 1397
Review 1300 of 1397
Review 1350 of 1397

In [18]:
# Fit a random forest to the training data, using 100 trees
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier( n_estimators = 100 )

print("Fitting a random forest to labeled training data...")
forest = forest.fit( trainDataVecs, train["author"] )

# Test & extract results 
result = forest.predict( testDataVecs )

# Write the test results 
output = pd.DataFrame( data={"true_author":test["author"], "pred_author":result} )
output.to_csv( "Word2Vec_AverageVectors.csv", index=False, quoting=3 )

Fitting a random forest to labeled training data...

In [19]:
print(output)

      true_author  pred_author
0              48           48
1              48           48
2              48           48
3              48           48
4              48           48
...           ...          ...
1392           48           48
1393           25           25
1394           48           48
1395           25           25
1396           48           48

[1397 rows x 2 columns]

In [20]:
confusion_matrix = pd.crosstab(output['true_author'], output['pred_author'], rownames=['Actural'], colnames=['Predicted'])
print(confusion_matrix)

Predicted   13   22   25   36   48
Actural
13         113    4   10    6    6
22           5  116    6    9   19
25           4    3  299    3   25
36           1    5   11  171   15
48          10    2   14    5  535

In [21]:
import sklearn
sklearn.metrics.confusion_matrix(output['true_author'], output['pred_author'])

array([[113,   4,  10,   6,   6],
       [  5, 116,   6,   9,  19],
       [  4,   3, 299,   3,  25],
       [  1,   5,  11, 171,  15],
       [ 10,   2,  14,   5, 535]], dtype=int64)

In [22]:
sklearn.metrics.precision_recall_fscore_support(output['true_author'], output['pred_author'], average=None)

(array([0.84962406, 0.89230769, 0.87941176, 0.8814433 , 0.89166667]),
 array([0.81294964, 0.7483871 , 0.89520958, 0.84236453, 0.94522968]),
 array([0.83088235, 0.81403509, 0.88724036, 0.86146096, 0.91766724]),
 array([139, 155, 334, 203, 566], dtype=int64))

In [23]:
pd.DataFrame(output.true_author.value_counts())

    true_author
48          566
25          334
36          203
22          155
13          139